version: '3.8'

services:
  localstack:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notification-localstack
    ports:
      - '4566:4566'
    environment:
      - SERVICES=sns,sqs,kms,lambda,iam
      - DEBUG=1
      - DATA_DIR=$HOME/Sites/projects/ga/tyfone/notification-service/tmp/localstack/data
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - localstack-data:$HOME/Sites/projects/ga/tyfone/notification-service/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - localstack-network

volumes:
  localstack-data:

networks:
  localstack-network:
    driver: bridge
